# Functions and Packages

sıklıkla gömülü fonksiyonları kullandık.

fonksiyonlar arkasında belli kod blokları olan, belli değerler alarak işlemleri gerçekleştiren yapılardır.

Örneğin:

len() fonksiyonu kaç elemanın bulunduğunu gösterir

print() fonksiyonu ekrana çıktı vermemizi sağlar

input() fonksiyonu kullanıcıdan veri alabilmemizi sağlar



In [ ]:
print('ekrana çıktı verdik')
print(len('karakter dizisi'))

ekrana çıktı verdik
15


**Methods**

değerlerimizin üzerinde değişiklik yapmaya yarayan özelliklere methodlar denir.

In [ ]:
# üzerine işlemler yapacağımız değerler
sister = 'liz'
height = 1.73
fam = ['liz',1.73, 'emma', 1.68,
       "mom", 1.71, "dad", 1.89]

In [ ]:
fam

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]

**index()**

Değerimizin kaçıncı indekste yer aldığını bulabilmemizi sağlayan methottur.

In [ ]:
fam.index('mom')

4

In [ ]:
falan = 'selamlar'
falan.index('l')

2

**count()**

Bir değerin kaç defa kullanıldığını gösteren methottur.

In [ ]:
fam.count('mom')

1

In [ ]:
sayilar = [1,2,4,1,5]
sayilar.count(1)

2

**capitalize()**

karakter dizisinin ilk harfini büyütür

In [ ]:
sister.capitalize()

'Liz'

**replace()**

karakter dizimin üzerinde ögeleri değiştirebilmemizi sağlayan bir methotdur.

In [ ]:
sister.replace('z','sa')

'lisa'

**append()**

Listeye öge eklemek için kullanılan bir methotdur.

In [ ]:
fam

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]

In [ ]:
fam.append('me')

In [ ]:
fam.append(12)
fam

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89, 'me', 'me', 12, 12]

**type()**

bir verinin veya değişkenin veri tipini öğreneblmemizi sağlayan fonksiyondur.

In [ ]:
type(fam)

list

# Packages

In [ ]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
import numpy
numpy.array([1,2,3])

array([1, 2, 3])

In [ ]:
from numpy import array
array([1,2,3])

array([1, 2, 3])

örneğin math paketini import ederek matematikle ilgili terimleri kodumuza dahil edebiliriz

In [ ]:
import math
print(math.pi)
math.ra

3.141592653589793
